#!/bin/bash
set -e

IGNORE_BEAM_OPENCV4=1
IGNORE_BEAM_CALIBRATION_=0
IGNORE_BEAM_COLORIZE_=1
IGNORE_BEAM_CONTAINERS_=1
IGNORE_BEAM_CV_=1
IGNORE_BEAM_DEFECTS_=1
IGNORE_BEAM_DEPTH_=1
IGNORE_BEAM_FILTERING_=0
IGNORE_BEAM_MAPPING_=0
IGNORE_BEAM_MATCHING_=1
IGNORE_BEAM_OPTIMIZATION_=1
IGNORE_BEAM_UTILS_=0

# Get important directories
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SRC_DIR="${SCRIPT_DIR//'/3d_map_builder/scripts'}"

# get number of processors for high-load installs
NUM_PROCESSORS=1
if [ $(nproc) -lt 2 ]; then
  NUM_PROCESSORS=1
else
  NUM_PROCESSORS=$(( $(nproc) / 2 ))
fi


echo "building your catkin workspace"
cd $SRC_DIR
cd ..
catkin build -j$NUM_PROCESSORS \
    -DCMAKE_IGNORE_BEAM_OPENCV4=$IGNORE_BEAM_OPENCV4 \
    -DCMAKE_IGNORE_BEAM_CALIBRATION=$IGNORE_BEAM_CALIBRATION_ \
    -DCMAKE_IGNORE_BEAM_COLORIZE=$IGNORE_BEAM_COLORIZE_ \
    -DCMAKE_IGNORE_BEAM_CONTAINERS=$IGNORE_BEAM_CONTAINERS_ \
    -DCMAKE_IGNORE_BEAM_CV=$IGNORE_BEAM_CV_ \
    -DCMAKE_IGNORE_BEAM_DEFECTS=$IGNORE_BEAM_DEFECTS_ \
    -DCMAKE_IGNORE_BEAM_DEPTH=$IGNORE_BEAM_DEPTH_ \
    -DCMAKE_IGNORE_BEAM_FILTERING=$IGNORE_BEAM_FILTERING_ \
    -DCMAKE_IGNORE_BEAM_MAPPING=$IGNORE_BEAM_MAPPING_ \
    -DCMAKE_IGNORE_BEAM_MATCHING=$IGNORE_BEAM_MATCHING_ \
    -DCMAKE_IGNORE_BEAM_OPTIMIZATION=$IGNORE_BEAM_OPTIMIZATION_ \
    -DCMAKE_IGNORE_BEAM_UTILS=$IGNORE_BEAM_UTILS_

